spring:
  application:
    name: ai-code-helper
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-5f6f291d29f34f43bca2a8b86365746d
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-5f6f291d29f34f43bca2a8b86365746d
bigmodel:
  api-key: 0781f81662df4b0dabb2ab1c35d1706b.oIWpypQsleYxv5gB